### ISSUE TITLE
feat[design]: ✨ add sd-menu + sd-menu-item

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#559]
- Moved description to new epic task (#1763)
- This task describes the implementation task for design and is closed.
- New plublishing task is mentioned in the epic task
- Story points have been removed as the effort was done in spring 2024

**Comment by coraliefeil** [comment]
For dropdown used as action menu.

Menu-items used in sd-dropdown are technically buttons that can be focused via keyboard arrows.

**Comment by karlbaumhauer** [comment]
result from pre-refinement:
Design starts with the components aligned with the existing shoelace version. Development will then follow on the design with #594

**Comment by coraliefeil** [comment]
@solid-design-system/core-development should this also be labeled with CL-Migration?

People need this comp to be able to fully replace this, right?

https://component-library.dev.fe.union-investment.de/integration/storybook/index.html?path=/story/components-dropdown--configurable

sd-dropdown is only a flyout with a slot.

**Comment by mariohamann** [comment]
Sorry to correct you – the sd-menu won't be a replacement for that. Again the sd-menu is more for applications, where the arrow keys are needed etc.

The stuff mentioned in the CMS is already doable, here's an example with navigation-items:

https://codepen.io/mariohamann/pen/poYOQmp

https://github.com/solid-design-system/solid/assets/26542182/08c27ce3-e96c-4ccb-b5d1-2f1cd8215d08

**Comment by karlbaumhauer** [comment]
@mariohamann your right... got mixed up again... removed the labels again... ;-)

**Comment by van-nguyen-ht** [comment]
per discussion with Mario, menu item will have a right arrow on the right and check to indicate selected menu item on the left & optional left icon

![Image](https://github.com/solid-design-system/solid/assets/118520877/41ea9b63-2c11-4607-a940-bff9adaa8b7d)
![Image](https://github.com/solid-design-system/solid/assets/118520877/bd13b3e9-07cd-4863-a543-111104d5c72c)

**Comment by coraliefeil** [comment]
@van-nguyen-ht left some more comments ... when you are done ... pls assign Ella for cd check.

**Comment by mariohamann** [comment]
Commented.

**Comment by van-nguyen-ht** [comment]
[Figma Branch ](https://www.figma.com/file/FXKazpLW1CbwevqkcgfUMx/sd-menu?type=design&node-id=15003-4416&mode=design)

Hi @karlbaumhauer I've implemented what we discussed. What I did: Menu item has the choice to use in combination or individually:
-icon-contained prop -> icon indent + icon boolean (can be toggled on if an icon is needed)
-check-contained prop -> check indent + check mark boolean (can be toggled on in case selection needed to be shown)

**Comment by karlbaumhauer** [comment]
> icon-contained prop

thx for the change @van-nguyen-ht 

TBH I am still not 100% happy with the naming. From a developer perspective, we either have 1 or 2 indentations for the checkmark and/or the icon (unfortunately even with 2 different widths).

If I imagine it right, we would have the prop `*icon` and `*checkmark` which are pure Figma-props as we would just use slots (even not sure about the checkmark). In addition we would have 2 props for dev and design, where we define the indentation... this seems very complex and I would like to have another session on that.

**Comment by van-nguyen-ht** [comment]
@karlbaumhauer yeah I think it'll be helpful to discuss this directly 

I place a photo of the current prop names here for ref

![Screenshot 2024-03-12 at 13 14 26](https://github.com/solid-design-system/solid/assets/118520877/52f3dfe0-7ea3-4a31-ae86-a7fbff0f40de)

**Comment by coraliefeil** [comment]
@karlbaumhauer if you could have another look into the discussion here once you are back ... that would be fantastic. THX

**Comment by van-nguyen-ht** [comment]
per discussion, the props will be renamed *icon-indented & *checkmark-indent

**Comment by coraliefeil** [comment]
So this one can be picked up once we are through with CL-Migration and focus on next things ...

**Comment by mariohamann** [comment]
This not an input component, so no, wouldn't say so.

**Comment by van-nguyen-ht** [comment]
@mariohamann 
I was talking with Coralie and I realized, for items that only select once and users can't revisit its selection state (those would have check mark), we don't need a selected + hovered. What do you think?

![Image](https://github.com/solid-design-system/solid/assets/118520877/a58b5b44-4fcd-40d2-90d0-1f165c6ebb9c)
